services:
    decrypt:
        image: python:3.9-slim
        container_name: decrypt_env
        volumes:
            - ./env:/app/env
        working_dir: /app/env
        command: bash -c "
            ls -la
            && source vault-pass.env
            && pip install ansible-vault
            && echo $$VAULT_PASSWORD > vault-pass.txt
            && ansible-vault decrypt secrets.env --vault-password-file vault-pass.txt --output .env
            && rm -rf vault-pass.txt"
    redis:
        image: redis:latest
        container_name: redis_db
        depends_on:
            decrypt:
                condition: service_completed_successfully
        volumes:
            - ./env:/app/env
        working_dir: /app/env
        command: bash -c "
            ls -la
            && source .env
            && redis-server --requirepass $$REDIS_PASSWORD"
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "bash", "-c", "
                cd /app/env
                && source .env
                && redis-cli -a $$REDIS_PASSWORD ping"]
            interval: 1s
            timeout: 2s
            retries: 10
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        healthcheck:
            test: [ "CMD", "nc", "-vz", "localhost", "2181" ]
            interval: 10s
            timeout: 3s
            retries: 3
    broker:
        image: confluentinc/cp-kafka:7.3.0
        hostname: broker    
        container_name: broker
        depends_on:
            zookeeper:
                condition: service_healthy
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
        healthcheck:
            test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "broker:9092"]
            interval: 10s
            timeout: 10s
            retries: 5
        ports:
            - 9092:9092
    consumer:
        build: .
        container_name: consumer
        volumes:
            - ./env:/app/env
        command: bash -c "
            ls -la
            && python src/preprocess.py 
            && python src/train.py 
            && python src/predict.py -m LOG_REG -t func
            && coverage run src/unit_tests/test_preprocess.py
            && coverage run -a src/unit_tests/test_training.py
            && coverage run -a src/unit_tests/test_database.py
            && coverage report -m
            && (python src/kafka_consumer.py --model LOG_REG &)
            && touch /tmp/consumer-ready 
            && tail -f /dev/null"
        depends_on:
            decrypt:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
            broker:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "test -f /tmp/consumer-ready"]
            interval: 1m
            timeout: 10s
            start_period: 5m
            retries: 30
    web:
        build: .
        container_name: web
        volumes:
            - ./env:/app/env
        command: bash -c "
            ls -la
            && coverage run -a src/unit_tests/test_database.py
            && coverage run -a src/unit_tests/test_app.py
            && coverage report -m
            && (python src/app.py &) 
            && sleep 30
            && curl -X GET http://localhost:8000/
            && curl -X POST http://localhost:8000/predict \
                    -H 'Content-Type":" application/json' \
                    --data-binary @tests/test_0.json"
        depends_on:
            decrypt:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
            broker:
                condition: service_healthy
            consumer:
                condition: service_healthy
        ports:
            - 8000:8000
        image: zarus03/ml-big-data-lab-3:latest
